export { default as Google } from './Google.svg';
export { default as WellsFargo } from './WellsFargo.svg';
export { default as Stripe } from './Stripe.svg';
export { default as Pitch } from './Pitch.svg';
export { default as Greenlight } from './Greenlight.svg';
export { default as topcrm } from './topcrm.svg';
export { default as reduce } from './reduce.svg';
export { default as customer } from './customer.svg';
export { default as oneclick } from './oneclick.svg';
